name: 'MockAI'
description: 'Mocking OpenAI and other providers API Endpoints'
author: 'Jim Stripe'

inputs:
  server-port:
    description: 'Server Port'
    required: false
    default: '5002'
  mock-type:
    description: 'Mock Type'
    required: false
    default: 'random'
  mock-file-path:
    description: 'Mock File Path'
    required: false
    default: 'data/contents.txt'
  mock-file-separator:
    description: 'Mock File Separator'
    required: false
    default: '@@@@'
  response-delay-ms:
    description: 'Response Delay in ms'
    required: false
    default: '500'
  request-size-limit:
    description: 'Request Size Limit'
    required: false
    default: '10kb'
  context-limit:
    description: 'Context Limit'
    required: false
    default: '40000'
  down-rate:
    description: 'Down Rate'
    required: false
    default: '0'
  tokens-per-minute:
    description: 'Tokens Per Minute'
    required: false
    default: '-1'
  tokens-per-day:
    description: 'Tokens Per Day'
    required: false
    default: '-1'
  requests-per-minute:
    description: 'Requests Per Minute'
    required: false
    default: '-1'
  requests-per-day:
    description: 'Requests Per Day'
    required: false
    default: '-1'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        repository: 'polly3d/mockai'
        path: 'mockai'
    - uses: docker/build-push-action@v6
      with:
        context: mockai
        push: false
        load: true
        tags: mockai:latest
    - run: |
        docker run -d -p ${{ inputs.server-port }}:${{ inputs.server-port }} \
          -e SERVER_PORT=${{ inputs.server-port }} \
          -e MOCK_TYPE=${{ inputs.mock-type }} \
          -e MOCK_FILE_PATH=${{ inputs.mock-file-path }} \
          -e MOCK_FILE_SEPARATOR=${{ inputs.mock-file-separator }} \
          -e RESPONSE_DELAY_MS=${{ inputs.response-delay-ms }} \
          -e REQUEST_SIZE_LIMIT=${{ inputs.request-size-limit }} \
          -e CONTEXT_LIMIT=${{ inputs.context-limit }} \
          -e DOWN_RATE=${{ inputs.down-rate }} \
          -e TOKENS_PER_MINUTE=${{ inputs.tokens-per-minute }} \
          -e TOKENS_PER_DAY=${{ inputs.tokens-per-day }} \
          -e REQUESTS_PER_MINUTE=${{ inputs.requests-per-minute }} \
          -e REQUESTS_PER_DAY=${{ inputs.requests-per-day }} \
          mockai:latest
      shell: bash
    - name: sleep
      run: sleep 5
      shell: bash
branding:
  icon: 'cloud'
  color: 'blue'
