services:
  mockai:
    build:
      context: .
      dockerfile: Dockerfile
    image: mockai:latest
    ports:
      - "5002:5002"
    environment:
      - SERVER_PORT=5002
      - MOCK_TYPE=random
      - MOCK_FILE_PATH=data/contents.txt
      - MOCK_FILE_SEPARATOR="@@@@"
      - RESPONSE_DELAY_MS=500
<<<<<<< HEAD
      - CONTEXT_LIMIT=5
=======
      - CONTEXT_LIMIT=40000
>>>>>>> 5ae624266aa617c7fade414827a39f19750a2aa4
    volumes:
      - ./data:/app/data:ro
    command: pnpm start