services:
  mockai:
    build:
      context: .
      dockerfile: Dockerfile
    image: mockai:latest
    ports:
      - "5002:5002"
    environment:
      - SERVER_PORT=5002
      - MOCK_TYPE=random
      - MOCK_FILE_PATH=data/contents.txt
      - MOCK_FILE_SEPARATOR="@@@@"
      - RESPONSE_DELAY_MS=500
      - CONTEXT_LIMIT=40000
      - DOWN_RATE=0
      - TOKENS_PER_MINUTE = 10
      - TOKENS_PER_DAY = 100
      - REQUESTS_PER_MINUTE = 10
      - REQUESTS_PER_DAY = 100
    volumes:
      - ./data:/app/data:ro
    command: pnpm start
